name: Build and deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Show build output (debug)
        run: |
          echo "Working directory: $(pwd)"
          echo "List root files:";
          ls -la
          echo "Check dist exists and list contents:";
          if [ -d ./dist ]; then ls -la ./dist || true; echo "Disk usage:"; du -sh ./dist || true; else echo "./dist not found"; fi

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-artifact@v4
        with:
          name: pages
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
